[package]
name = "wgpu_util"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.12"
wgpu = "26.0.1"
anyhow = "1.0.100"
log = "0.4.28"
env_logger = "0.11.8"
tokio = { version = "1.47.1", features = ["rt", "rt-multi-thread"] }
